language: bash

sudo: required

services:
  - docker

before_script:
    - CURDIR=$PWD
    - ./edjangerinstall.sh --alias
    - git clone --branch=master https://github.com/sstephenson/bats.git /tmp/bats
    - cd /tmp/bats; ./install.sh /home/travis; rm -rf /tmp/bats
    - curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /home/travis/docker-compose
    - chmod +x /home/travis/docker-compose
    - curl -L https://github.com/docker/machine/releases/download/v0.8.2/docker-machine-`uname -s`-`uname -m` >/home/travis/docker-machine
    - chmod +x /home/travis/docker-machine
    - cd $CURDIR/tests

script:
    - bats --tap edjanger_tests.bats
    
